### PR TITLE
Support syn::File case for module level document

### LINKED ISSUE #1: Support for module-level docs
Is there a way to make this crate work with module-level docs?

I've tried https://github.com/termoshtt/katexit/compare/main...maoe:module-level with no luck.

### PR DESCRIPTION
**Pull request by termoshtt**
Resolve #1

### CODE REVIEW

**Comment by termoshtt** [comment]
There are two problems:

- Custom inner attributes is not supported in stable Rust https://github.com/rust-lang/rust/issues/54726

```
error[E0658]: inner macro attributes are unstable
 --> katexit-example/src/lib.rs:1:4                                                 
  |
1 | #![katexit::katexit]                                                            
  |    ^^^^^^^^^^^^^^^^
  |                                                                                 
  = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726> for more information
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable
```

- `cargo +nightly --doc` does not works:

```
error[E0658]: `#[prelude_import]` is for use by rustc only
  --> katexit-example/src/lib.rs:1:1
   |
1  | / #![feature(custom_inner_attributes)]
2  | | #![katexit::katexit]
3  | | //! Module level document example
4  | |
...  |
13 | | /// $$
14 | | pub fn my_func() {}
   | |___________________^
   |
   = help: add `#![feature(prelude_import)]` to the crate attributes to enable

error: Compilation failed, aborting rustdoc
```

**Comment by Andlon** [comment]
Seems like it could perhaps work now? This seems to actually work on nightly with your branch:
```rust
#![feature(custom_inner_attributes)]
#![feature(prelude_import)]
#![cfg_attr(doc, katexit::katexit)]
//! Test $x = 2$.
//!
//! <div>$$
//! \iiint_{\Omega} f(x) \, \mathrm{d}x
//! $$</div>
fn main() {}
```
image

Which is exciting, to say the least :-) I'm not sure about the implications of this - how "stable" is this? I'm not sure if we can deploy a solution like this to `docs.rs` since there is no way to pin the `nightly` version on there. Promising, nonetheless!

**Comment by termoshtt** [comment]
I confirm this works with `cargo 1.66.0-nightly (3ff044334 2022-10-17)`. Thanks :)
